### ISSUE TITLE
対象文字が被ると思う

### ISSUE THREAD

**Issue by c0a21024b3** [KIN0417/ProjExD#3]
この書き方だと同じアルファベットを対象文字に指定することがあるから、
if moji[a] not in q
でqに入っていない場合の条件を付けたほうがいいと思う
https://github.com/KIN0417/ProjExD/blob/001f0cc8cd8038910f40b1cdb84a7854e6134e31/ex01/search.py#L12

**Comment by KIN0417** [comment]
popで取り出してるのでかぶらないです

**Comment by c0a21024b3** [comment]
勘違いでした
